
# POST http://localhost:3001/api/notes/
# content-type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJNYWhhZGlAbWFpbC5jb20iLCJpZCI6IjYzOGRhZTRkMjNlMmRkZDdhODMwNDE5MSIsImlhdCI6MTY3MDIyOTY3OCwiZXhwIjoxNjcwMjMwNTc4fQ.U8aqioIu_zB-QGk_NjwD1Zt9DKkO95Ux_CB8FxfthdY

# {   
#     "label": "A tale of blood and iron",
#     "content": "This is the content of a tale of blood and iron"
# }
      

POST http://localhost:3001/api/notes/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJTaGVyaWZmQG1haWwuY29tIiwiaWQiOiI2MzhkYWU2MTIzZTJkZGQ3YTgzMDQxOTQiLCJpYXQiOjE2NzQwNTAzNzQsImV4cCI6MTY3NDEzNjc3NH0.k8RTqjX6cU9O79mKDak7u8XXq4-fjp3uDs-gPIfuku0

{   
    "label": "test2",
    "content": "test with group 2",
    "groupname": "testgroup"
} 















# let notes = [
#     {   
#         id: 1,
#         label: 'A tale of iron and blood',
#         content: 'This is the content of a tale of iron and blood',
#         created: '2022-01-10T17:30:31.098Z',
#         modified: '2022-01-10T17:30:31.098Z',
#     },
#     {   
#         id: 2,
#         label: 'Sword and fire',
#         content: 'This is the content of sword and fire',
#         created: '2022-02-10T17:30:31.098Z',
#         modified: '2022-02-10T17:30:31.098Z',
#     },
#     {   
#         id: 3,
#         label: 'A tale of wind and fire',
#         content: 'This is the content of a tale of wind and fire',
#         created: '2022-03-10T17:30:31.098Z',
#         modified: '2022-03-10T17:30:31.098Z',
#     },
#     {   
#         id: 4,
#         label: 'Arash the sun god',
#         content: 'This is the content arash the sun god',
#         created: '2022-04-10T17:30:31.098Z',
#         modified: '2022-04-10T17:30:31.098Z',
#     },
# ]
