GET http://localhost:3001/api/notes/6390376101a901e9e3303cfe
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJTaGVyaWZmQG1haWwuY29tIiwiaWQiOiI2MzhkYWU2MTIzZTJkZGQ3YTgzMDQxOTQiLCJpYXQiOjE2NzAzOTY3NTEsImV4cCI6MTY3MDM5NzY1MX0.fa7NeNKZCTTstOKPrkbj63OcRqYe36ikCohlgoGuiOQ
